[project]
name = "gemini-api"
version = "0.1.0"
description = "A real estate market report generator based on structured JSON data and texts generated using the Gemini model."
authors = [
    {name = "Sozonov_Ilushka",email = "113029719+sozozzya@users.noreply.github.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
